import type { ProductI } from './types';
import { uuid, utils } from '@/shared/lib';

export const popularProduct = [
  {
    id: uuid.uuid(),
    title: 'Хачапури по-аджарски',
    price: 470,
    image: utils.getImage('img/dishes/хачапури по-аджарски.png'),
    des: 'Хачапури "Лодочка" с начинкой из расплавленного сыра сулугуни, яйца и масла',
    weight: 430,
  },
  {
    id: uuid.uuid(),
    title: 'Хинкали традиционные (6шт)',
    price: 495,
    image: utils.getImage('img/dishes/Хинкали традиционные.png'),
    des: 'Пряные хинкали с начинкой из ароматной баранины со специями.',
    weight: 350,
  },
  {
    id: uuid.uuid(),
    title: 'Хинкали жаренные (6шт)',
    price: 520,
    image: utils.getImage('img/dishes/Хинкали жаренные.png'),
    des: 'Пряные хинкали с начинкой из ароматной баранины со специями.',
    weight: 350,
  },
  {
    id: uuid.uuid(),
    title: 'Ланч низкокалорийный',
    price: 1148,
    image: utils.getImage('img/dishes/ланч-низкокалорийный.png'),
    des: 'Греческий йогурт с ягодами, 3 хинкали традиционных, салат цезарь, пирожки с уткой, морс',
    weight: 450,
  },
  {
    id: uuid.uuid(),
    title: 'Хачапури по-мегрельски',
    price: 490,
    image: utils.getImage('img/dishes/Хачапури по-мегрельски.png'),
    des: 'Невероятно ароматная лепёшка с сыром сулугуни внутри и снаружи',
    weight: 430,
  },
  {
    id: uuid.uuid(),
    title: 'Котлета с картофелем по-деревенски',
    price: 430,
    image: utils.getImage('img/dishes/котлета по-деревенски.png'),
    des: 'По семейному рецепту: нежнейшее рубленное мясо с экологически чистыми ферме...',
    weight: 350,
  },
  {
    id: uuid.uuid(),
    title: 'Хинкали традиционные (6шт)',
    price: 495,
    image: utils.getImage('img/dishes/Хинкали традиционные.png'),
    des: 'Пряные хинкали с начинкой из ароматной баранины со специями.',
    weight: 350,
  },
  {
    id: uuid.uuid(),
    title: 'Хачапури по-мегрельски',
    price: 490,
    image: utils.getImage('img/dishes/хачапури по мегрельски.png'),
    des: 'Невероятно ароматная лепёшка с сыром сулугуни внутри и снаружи',
    weight: 430,
  },
  {
    id: uuid.uuid(),
    title: 'Хачапури по-аджарски',
    price: 470,
    image: utils.getImage('img/dishes/хачапури.png'),
    des: 'Хачапури "Лодочка" с начинкой из расплавленного сыра сулугуни, яйца и масла.',
    weight: 430,
  },
  {
    id: uuid.uuid(),
    title: 'Котлета с картофелем по-деревенски',
    price: 430,
    image: utils.getImage('img/dishes/img1.png'),
    des: 'По семейному рецепту: нежнейшее рубленное мясо с экологически чистыми ферме...',
    weight: 350,
  },
  {
    id: uuid.uuid(),
    title: 'Хинкали жаренные (6шт)',
    price: 520,
    image: utils.getImage('img/dishes/img2.png'),
    des: 'Пряные хинкали с начинкой из ароматной баранины со специями.',
    weight: 350,
  },
  {
    id: uuid.uuid(),
    title: 'Ланч низкокалорийный',
    price: 1148,
    image: utils.getImage('img/dishes/ланч низкокалорийный.png'),
    des: 'Греческий йогурт с ягодами, 3 хинкали традиционных, салат цезарь, пирожки с уткой, морс',
    weight: 450,
  },
] as const satisfies ProductI[];
